# Generated by Django 4.2.1 on 2023-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='number_of_drugs',
            field=models.IntegerField(blank=True, default=0, help_text='Кількість препарату'),
        ),
    ]
