# Generated by Django 4.2.1 on 2023-05-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drugs_number_of_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='photo',
            field=models.TextField(blank=True, help_text='Фото'),
        ),
    ]
