# Generated by Django 4.2.1 on 2023-05-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_drugs_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='type',
        ),
        migrations.AddField(
            model_name='drugs',
            name='category',
            field=models.CharField(blank=True, help_text='Категорія препарату (протизастудні, знеболюючі і т.д.)', max_length=100),
        ),
        migrations.AddField(
            model_name='drugs',
            name='form',
            field=models.CharField(blank=True, help_text='Форма випуску препарату (сироп, таблетки і т.д.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='photo',
            field=models.TextField(blank=True, default='', help_text='Фото препарату'),
        ),
    ]
