# Generated by Django 4.2.1 on 2023-05-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_drugs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='category',
        ),
        migrations.AddField(
            model_name='drugs',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Категорія препарату (протизастудні, знеболюючі і т.д.)', to='main.categories'),
        ),
    ]
