# Generated by Django 4.2.1 on 2023-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categories_remove_drugs_category_drugs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='drugs',
            name='form',
        ),
        migrations.AddField(
            model_name='drugs',
            name='form',
            field=models.ManyToManyField(blank=True, help_text='Форма випуску препарату (сироп, таблетки і т.д.)', to='main.forms'),
        ),
    ]
