# Generated by Django 4.2.1 on 2023-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_countryoforigin_remove_drugs_country_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Опис')),
                ('price', models.FloatField(blank=True, help_text='Ціна')),
                ('datetime_of_operation', models.DateTimeField(blank=True, help_text='Дата виготовлення')),
            ],
        ),
    ]
